### PR TITLE
Update ViewPump library dependency

### LINKED ISSUE #11: Migrate to AndroidX

### PR DESCRIPTION
**Pull request by pr0t3us**
Updated [ViewPump](https://github.com/InflationX/ViewPump) library to `2.0.3` since it's gone too far by the version number.
ViewPump [migrated]( https://developer.android.com/jetpack/androidx/migrate) the project to [AndroidX](https://developer.android.com/jetpack/androidx/) in the `2.0.0` version, so now is the time to move the `Philology` to `AndroidX`.
According to Google the support library artifacts are being deprecated and all future development is going into `AndroidX`, so there's no avoiding this migration.

Resolves https://github.com/JcMinarro/Philology/issues/11

### CODE REVIEW

**Comment by JcMinarro** [comment]
Hi @pr0t3us 
Yes, it is the natural way to improve it, but It would be a breaking change. There is not problem, we will release it as a major version when it is completed.
The PR seems fine, but we need to fix the CI.
I can see you updated the Target SDK Version, so we will need to update the Docker Image Version used on CircleCI

**Comment by pr0t3us** [comment]
@JcMinarro Updated CircleCI docker image version to 28 and all the checks have been passed.

**Comment by egor-n** [comment]
@JcMinarro Philology is one of the libraries keeping us from removing the Jetifier. Do you think you will be able to review the PR in the near future? 🙏

**Comment by JcMinarro** [comment]
Sorry for the delay, I will merge and publish a new version this afternoon

**Review by JcMinarro — APPROVED** [review]

**Comment by JcMinarro** [comment]
Good job @pr0t3us

**Pull request merged**
